### ISSUE TITLE
Seatsio don't allow to create event on the chart in different workspace

### ISSUE THREAD

**Issue by hos** [wylling/wylling#27]
Seatsio don't allow to create events on charts that are not in same workspace. There are possibly 2 workarounds.

1. Always use same workspace for all events and charts. This will effect #18, if we will go with first solution.
2. Before creating event, copy the chart to the workspace of the event creator.

The first is dangerous, as we will expose the secrets in the browser for seats designer and event manager. And any user that have access to any of the charts or events, will have access to other's, even though it not belongs to that user.

The second solution will require some code changes. When event is approved on the place, we need to

1. If event is in the same company with the place, we can create event immediately.
2. If event company differs from the place's company, we need to copy the chart from the place company workspace to the event creator and keep the new chart key on the event case. This way event will refer to same place always but to different chart technically. So though visually they may be the same chart, technically they will have different IDs.

To go with second solution we need to find all usages of chat key, that we read from `place.chartKey` and see if we can replace it with `eventCase.chartKey`. This will not effect chart designer as it must use the workspace of the original chart.

**Comment by tigrankeshishyan** [comment]
the second solution looks better. Only the thing that we have to do is make that "snapshot" chart editable.
there can be situations when the user will want to add some seats or remove some seats after when event created.
We don't restrict changes for charts at this moment.
And another thing for the future maybe. What if we will create tons of charts and one day will face a problem with the count of cahrts? What if seats.io will block it someday?

**Comment by hos** [comment]
> Only the thing that we have to do is make that "snapshot" chart editable.

Charts are editable by default for the workspace that contains the chart. If you need to allow editing the chart to the event creator, then event creator is able to edit carts in own workspace. So this will work by default too. This functionality is not something we can control from our side, please look into seatsio docs for more specific answers.

> there can be situations when the user will want to add some seats or remove some seats after when event created.

If by `user` you mean the event creator, then again event creator will be able to edit the cart as he/she have access to workspace secret key.

> And another thing for the future maybe. What if we will create tons of charts and one day will face a problem with the count 
of cahrts? What if seats.io will block it someday?

Not related to this topic. We can run out limits with or without this feature. Consider opening another issue to find out seatsio limits.

**Comment by tigrankeshishyan** [comment]
ok. then we can implement the second version if it the right way to do
